.TH "SIMPLEBOT" "1" "2016-10-28" "GNU" "Program Doc"

.SH NAME
SimpleBot \- a simple Chatbot talking in German 

.SH SYNOPSIS

.B simplebot

.SH DESCRIPTION
.Nm
Opens a command line which can be used to chat with the bot. The program does not read from stdin. Its German-speaking abilities are limited so far.
Additional documentation can be found in the doc directory in the source.

.SH ENVIRONMENT
Requires SWI-Prolog to be installed on the system.

.SH AUTHOR
Jörg Strebel (joerg.strebel@gmail.com)

.SH SEE ALSO

